window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']],
    macros : {
      s: '{\\mathrm{s}}',
      min: '{\\mathrm{min}}',
      hr: '{\\mathrm{hr}}',
      kg: '{\\mathrm{kg}}',
      slug: '{\\mathrm{slugs}}',
      N: '{\\mathrm{N}}',
      kN: '{\\mathrm{kN}}',
      inch: '{\\mathrm{in}}',
      ft: '{\\mathrm{ft}}',
      m: '{\\mathrm{m}}',
      mm: '{\\mathrm{mm}}',
      km: '{\\mathrm{km}}',
      mi: '{\\mathrm{mi}}',
      mph: '{\\mathrm{mph}}',
      cm: '{\\mathrm{cm}}',
      lb: '{\\mathrm{lb}}',
      lbm: '{\\mathrm{lbm}}',
      lbf: '{\\mathrm{lbf}}',
      Pa: '{\\mathrm{Pa}}',
      kPa: '{\\mathrm{kPa}}',
      MPa: '{\\mathrm{MPa}}',
      psi: '{\\mathrm{psi}}',
      C: '{^\\circ\\mathrm{C}}',
      F: '{^\\circ\\mathrm{F}}',
      R: '{\\mathrm{R}}',
      K: '{\\mathrm{K}}',
      gal: '{\\mathrm{gal}}',
      L: '{\\mathrm{L}}',
      cfm: '{\\mathrm{cfm}}',
      fps: '{\\mathrm{fps}}',
      fpm: '{\\mathrm{fpm}}',
      gpm: '{\\mathrm{gpm}}',
      lpm: '{\\mathrm{L}/\\mathrm{min}}',
      sg: '{\\mathrm{sg}}',
      Re: '{\\mathrm{Re}}',
      WP: '{\\mathrm{WP}}',
      inWC: '{\\mathrm{inH}_2\\mathrm{O}}',
      hp: '{\\mathrm{hp}}',
      lbftovs: '{\\mathrm{lb}\\cdot\\mathrm{ft}/\\mathrm{s}}',
    }
  },
  svg: {
    fontCache: 'global'
  }
};
